[global]
frame_color = "#272C2F"
separator_color = frame

highlight = "#AEE6F0"

[urgency_low]
background = "#1F2225"
foreground = "#859296"
frame_color = "#33383C"

[urgency_normal]
background = "#1F2225"
foreground = "#E9F2F2"
frame_color = "#272C2F"

[urgency_critical]
background = "#1F2225"
foreground = "#E9F2F2"
frame_color = "#F07E9F"