background               #181A1C
foreground               #E9F2F2
selection_foreground     #E9F2F2
selection_background     #33383C

cursor                   #E9F2F2
cursor_text_color        #181A1C

url_color                #EBC56C

active_tab_foreground    #E9F2F2
active_tab_background    #181A1C
inactive_tab_foreground  #586266
inactive_tab_background  #1F2225

active_border_color      #272C2F
inactive_border_color    #33383C

color0   #181A1C
color8   #33383C
color1   #F07E9F
color9   #F5A0B0
color2   #4FA3C0
color10  #6BBFD0
color3   #EBC56C
color11  #F5D080
color4   #AEE6F0
color12  #C0F0F8
color5   #C1A9E8
color13  #D0B8F0
color6   #F2A49E
color14  #F5B8B0
color7   #E9F2F2
color15  #F5F8F8