palette = 0=#181A1C
palette = 1=#F07E9F
palette = 2=#4FA3C0
palette = 3=#EBC56C
palette = 4=#AEE6F0
palette = 5=#C1A9E8
palette = 6=#F2A49E
palette = 7=#E9F2F2

palette = 8=#33383C
palette = 9=#F5A0B0
palette = 10=#6BBFD0
palette = 11=#F5D080
palette = 12=#C0F0F8
palette = 13=#D0B8F0
palette = 14=#F5B8B0
palette = 15=#F5F8F8

background = #181A1C
foreground = #E9F2F2
cursor-color = #E9F2F2
cursor-text = #181A1C
selection-background = #33383C
selection-foreground = #E9F2F2