"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false 
command_timeout = 200
format = "$hostname$directory$git_branch$git_status$character"

[character]
error_symbol   = "[›](bold #F07E9F)"
success_symbol = "[›](bold #AEE6F0)"   

[directory]
truncation_length = 3
truncation_symbol = "../"
style = "bold #BFD6D8"
repo_root_style = "bold #BFD6D8"   
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "#859296"

[git_branch]
format = "[$branch]($style) "
style = "#859296"

[git_status]
format = "[$conflicted](bold #F07E9F)"
conflicted = "!"